# -*- coding: utf-8 -*-
"""Question Two (a) - PEAS and PAGE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMeDYkbhhrddkvloIdlK7g34AFfTG62j
"""

print("\n" + "="*60)
print("DNA AND GENOMIC SEQUENCING SYSTEM - PEAS & PAGE")
print("="*60)

peas = {
    "Performance Measure": [
        "Accuracy of DNA matching (≥99.99%)",
        "Speed of identification (< 24 hours per sample)",
        "Number of successful identifications",
        "False positive/negative rate (< 0.001%)",
        "Sample throughput per day",
        "Cost per identification"
    ],
    "Environment": [
        "Laboratory with DNA sequencing equipment",
        "Database of victim and relative samples",
        "Temperature-controlled storage units",
        "Network-connected computing cluster",
        "Clean room environment (ISO Class 5)",
        "Chain-of-custody tracking system"
    ],
    "Actuators": [
        "DNA sequencer controller",
        "Sample robotic handler",
        "Database query interface",
        "Report generator",
        "Alert notification system",
        "Temperature regulator",
        "Printer for identification certificates"
    ],
    "Sensors": [
        "DNA sequencer raw data reader",
        "Barcode/RFID sample scanner",
        "Temperature/humidity sensors",
        "Camera for sample tracking",
        "Database connection status monitor",
        "Quality control sensors",
        "Chain-of-custody scanner"
    ]
}

page = {
    "Percepts": [
        "Raw DNA sequence data from sequencer",
        "Sample IDs from barcode scanners",
        "Reference DNA profiles from database",
        "Environmental conditions (temp, humidity)",
        "Quality scores for sequencing runs",
        "Chain-of-custody timestamps",
        "Equipment calibration status"
    ],
    "Actions": [
        "INITIATE_SEQUENCING(sample_id)",
        "COMPARE_WITH_DATABASE(dna_sequence)",
        "GENERATE_MATCH_REPORT(confidence_level)",
        "ALERT_AUTHORITIES(match_found)",
        "UPDATE_CHAIN_OF_CUSTODY(sample_id, status)",
        "REQUEST_RE_SEQUENCE(sample_id)",
        "ARCHIVE_RESULTS(victim_id, match_info)",
        "CALIBRATE_EQUIPMENT()"
    ],
    "Goals": [
        "Identify ≥95% of victims within 30 days",
        "Maintain zero false identifications",
        "Process 1000+ samples per day",
        "Complete analysis within 24 hours per batch",
        "Maintain complete audit trail",
        "Ensure data privacy and security"
    ],
    "Environment": [
        "DNA samples from Shakahola victims (decomposed)",
        "Reference DNA from relatives",
        "Laboratory infrastructure",
        "Database of missing persons",
        "Legal and ethical framework",
        "Cross-referencing with other identification methods"
    ]
}

print("\n📊 PEAS FRAMEWORK:")
for key, values in peas.items():
    print(f"\n  {key.upper()}:")
    for v in values:
        print(f"    • {v}")

print("\n\n📋 PAGE FRAMEWORK:")
for key, values in page.items():
    print(f"\n  {key.upper()}:")
    for v in values:
        print(f"    • {v}")