# -*- coding: utf-8 -*-
"""Question 1b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2rHm9dCSD3mOGAi0ATcN5ZQkpl0Nl4r
"""

# A* Search Algorithm for Path Optimization
# Run this on Google Colab

import heapq
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple, Dict, Set
import time

class Node:
    """Represents a node in the search space"""
    def __init__(self, position: Tuple[int, int], parent=None):
        self.position = position
        self.parent = parent
        self.g = 0  # Cost from start to current node
        self.h = 0  # Heuristic cost to goal
        self.f = 0  # Total cost (g + h)

    def __lt__(self, other):
        return self.f < other.f

    def __eq__(self, other):
        return self.position == other.position

class AStarPathOptimizer:
    """
    A* Search Strategy for path resource optimization.
    Finds the optimal path while minimizing cost/distance.
    """

    def __init__(self, grid: np.ndarray):
        """
        Initialize the A* optimizer.

        Args:
            grid: 2D array where 0 = free, 1 = obstacle
        """
        self.grid = grid
        self.rows, self.cols = grid.shape

    def heuristic(self, current: Tuple[int, int], goal: Tuple[int, int]) -> float:
        """
        Heuristic function - Euclidean distance (admissible).
        Also supports Manhattan distance for grid movement.

        Returns estimated cost to goal.
        """
        # Euclidean distance (better for diagonal movement)
        return np.sqrt((current[0] - goal[0])**2 + (current[1] - goal[1])**2)

        # Alternative: Manhattan distance (for 4-direction movement)
        # return abs(current[0] - goal[0]) + abs(current[1] - goal[1])

    def get_neighbors(self, node: Node) -> List[Tuple[int, int]]:
        """
        Get valid neighboring positions (4-direction movement).
        """
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]  # Right, Down, Left, Up
        neighbors = []

        for dx, dy in directions:
            new_x, new_y = node.position[0] + dx, node.position[1] + dy

            # Check bounds and obstacles
            if (0 <= new_x < self.rows and 0 <= new_y < self.cols and
                self.grid[new_x][new_y] == 0):
                neighbors.append((new_x, new_y))

        return neighbors

    def search(self, start: Tuple[int, int], goal: Tuple[int, int]) -> Tuple[List[Tuple[int, int]], Dict]:
        """
        Perform A* search to find optimal path.

        Returns:
            path: List of positions from start to goal
            stats: Dictionary with search statistics
        """
        start_time = time.time()

        # Initialize
        start_node = Node(start)
        goal_node = Node(goal)

        open_list = []  # Priority queue
        closed_set = set()  # Visited nodes
        open_dict = {}  # For quick lookup

        start_node.g = 0
        start_node.h = self.heuristic(start, goal)
        start_node.f = start_node.g + start_node.h

        heapq.heappush(open_list, start_node)
        open_dict[start] = start_node

        nodes_explored = 0

        while open_list:
            current_node = heapq.heappop(open_list)
            nodes_explored += 1

            # Check if we reached goal
            if current_node.position == goal:
                path = self.reconstruct_path(current_node)
                elapsed_time = time.time() - start_time

                stats = {
                    'path_length': len(path),
                    'path_cost': current_node.g,
                    'nodes_explored': nodes_explored,
                    'time_taken': elapsed_time,
                    'open_list_size': len(open_list),
                    'closed_set_size': len(closed_set)
                }
                return path, stats

            closed_set.add(current_node.position)

            # Explore neighbors
            for neighbor_pos in self.get_neighbors(current_node):
                if neighbor_pos in closed_set:
                    continue

                # Calculate tentative g score
                tentative_g = current_node.g + 1  # Uniform cost for each move

                neighbor_node = open_dict.get(neighbor_pos)

                if neighbor_node is None:
                    # Create new node
                    neighbor_node = Node(neighbor_pos, current_node)
                    neighbor_node.g = tentative_g
                    neighbor_node.h = self.heuristic(neighbor_pos, goal)
                    neighbor_node.f = neighbor_node.g + neighbor_node.h
                    open_dict[neighbor_pos] = neighbor_node
                    heapq.heappush(open_list, neighbor_node)

                elif tentative_g < neighbor_node.g:
                    # Better path found
                    neighbor_node.parent = current_node
                    neighbor_node.g = tentative_g
                    neighbor_node.f = neighbor_node.g + neighbor_node.h

        # No path found
        return [], {'error': 'No path exists', 'nodes_explored': nodes_explored}

    def reconstruct_path(self, node: Node) -> List[Tuple[int, int]]:
        """Reconstruct path from goal to start by following parents."""
        path = []
        current = node
        while current is not None:
            path.append(current.position)
            current = current.parent
        return path[::-1]  # Reverse to get start -> goal

def visualize_path(grid: np.ndarray, path: List[Tuple[int, int]],
                   start: Tuple[int, int], goal: Tuple[int, int]):
    """Visualize the grid and the found path."""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Create colormap
    cmap = plt.cm.colors.ListedColormap(['white', 'black', 'green', 'red', 'blue'])
    bounds = [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]
    norm = plt.cm.colors.BoundaryNorm(bounds, cmap.N)

    # Create visualization grid
    vis_grid = grid.copy().astype(float)

    # Mark start and goal
    vis_grid[start] = 2  # Green for start
    vis_grid[goal] = 3   # Red for goal

    # Mark path
    for pos in path[1:-1]:  # Exclude start and goal
        vis_grid[pos] = 4    # Blue for path

    ax.imshow(vis_grid, cmap=cmap, norm=norm, origin='upper')

    # Add grid lines
    ax.set_xticks(np.arange(-0.5, grid.shape[1], 1), minor=True)
    ax.set_yticks(np.arange(-0.5, grid.shape[0], 1), minor=True)
    ax.grid(which='minor', color='gray', linestyle='-', linewidth=0.5)

    ax.set_title(f'A* Path Optimization - Path Length: {len(path)}', fontsize=14)
    ax.set_xlabel('Columns')
    ax.set_ylabel('Rows')

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='white', label='Free Space'),
        Patch(facecolor='black', label='Obstacle'),
        Patch(facecolor='green', label='Start'),
        Patch(facecolor='red', label='Goal'),
        Patch(facecolor='blue', label='Path')
    ]
    ax.legend(handles=legend_elements, loc='upper right')

    plt.tight_layout()
    plt.show()

def run_demo():
    """Demonstrate A* algorithm with multiple scenarios."""

    # Create different grid environments
    scenarios = [
        {
            'name': 'Simple Open Grid',
            'grid': np.zeros((10, 10), dtype=int),
            'start': (0, 0),
            'goal': (9, 9)
        },
        {
            'name': 'Grid with Obstacles',
            'grid': np.zeros((12, 12), dtype=int),
            'start': (0, 0),
            'goal': (11, 11),
            'obstacles': [(3, 3), (3, 4), (4, 3), (4, 4), (5, 5), (5, 6), (6, 5), (6, 6),
                          (7, 2), (7, 3), (8, 2), (8, 3), (2, 7), (3, 7), (2, 8), (3, 8)]
        },
        {
            'name': 'Maze-like Environment',
            'grid': np.zeros((15, 15), dtype=int),
            'start': (0, 0),
            'goal': (14, 14),
            'obstacles': [(i, 7) for i in range(15) if i != 0 and i != 14] +  # Vertical wall
                         [(7, i) for i in range(15) if i != 7]  # Horizontal wall
        }
    ]

    # Add obstacles for scenarios that have them
    for i, scenario in enumerate(scenarios):
        if 'obstacles' in scenario:
            for obs in scenario['obstacles']:
                scenario['grid'][obs] = 1

    # Run each scenario
    for scenario in scenarios:
        print(f"\n{'='*60}")
        print(f"Scenario: {scenario['name']}")
        print(f"{'='*60}")

        astar = AStarPathOptimizer(scenario['grid'])
        path, stats = astar.search(scenario['start'], scenario['goal'])

        if path:
            print(f"✓ Path found!")
            print(f"  Path length: {stats['path_length']} steps")
            print(f"  Total cost: {stats['path_cost']}")
            print(f"  Nodes explored: {stats['nodes_explored']}")
            print(f"  Time taken: {stats['time_taken']:.5f} seconds")
            print(f"  Path: {path[:5]}...{path[-3:]}")

            visualize_path(scenario['grid'], path, scenario['start'], scenario['goal'])
        else:
            print(f"✗ No path found: {stats.get('error', 'Unknown error')}")

# Run the demonstration
if __name__ == "__main__":
    print("="*60)
    print("A* SEARCH STRATEGY FOR PATH RESOURCE OPTIMIZATION")
    print("="*60)
    print("\nA* algorithm uses:")
    print("  - g(n): Actual cost from start to node n")
    print("  - h(n): Heuristic estimate to goal (Euclidean distance)")
    print("  - f(n) = g(n) + h(n) → prioritized for exploration")
    print("  - Guarantees optimal path with admissible heuristic")

    run_demo()