# -*- coding: utf-8 -*-
"""Question One (c)(ii) - Truth Table

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcWHwaJ5wJVC2KBVzkSjZvctZ6XT0Slt
"""

# Truth Table for P ∧ Q → R
print("\n" + "="*60)
print("TRUTH TABLE: P ∧ Q → R")
print("="*60)
print(f"{'P':^5} {'Q':^5} {'R':^5} {'P∧Q':^8} {'P∧Q→R':^10} {'Status':^12}")
print("-"*50)

import itertools

for p, q, r in itertools.product([True, False], repeat=3):
    p_and_q = p and q
    result = (not p_and_q) or r  # Implication: A→B ≡ ¬A ∨ B

    # Determine status
    if result:
        status = "Satisfied"
    else:
        status = "Falsified"

    print(f"{str(p)[0]:^5} {str(q)[0]:^5} {str(r)[0]:^5} "
          f"{str(p_and_q)[0]:^8} {str(result)[0]:^10} {status:^12}")

print("\n" + "="*60)
print("ANALYSIS:")
print("="*60)
print("""• VALID? NO - Formula is false when P=TRUE, Q=TRUE, R=FALSE
• SATISFIABLE? YES - True in 7 out of 8 interpretations
• UNSATISFIABLE? NO - Not false in all interpretations
• FALSIFIABLE? YES - False when (P∧Q) is TRUE and R is FALSE

CONDITIONS:
- True when: (P∧Q) is FALSE OR R is TRUE
- False only when: P=TRUE, Q=TRUE, R=FALSE
""")