# -*- coding: utf-8 -*-
"""Question Two (b) - Vacuum Cleaner Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcYQ1PESEFH60Qt5-DtQX0-DvCJ3JrqL
"""

# Simple Vacuum Cleaner Agent
# Run this on Google Colab

import random
import time
import matplotlib.pyplot as plt
import numpy as np
from enum import Enum
from typing import Tuple, List, Dict
import copy

class Action(Enum):
    """Possible actions for the vacuum cleaner"""
    MOVE_UP = "↑"
    MOVE_DOWN = "↓"
    MOVE_LEFT = "←"
    MOVE_RIGHT = "→"
    SUCK = "🧹"
    IDLE = "💤"

class LocationState(Enum):
    """State of a location"""
    CLEAN = "●"
    DIRTY = "○"

class VacuumCleanerAgent:
    """
    Simple reflex agent for vacuum cleaning.
    Implements a logical agent that cleans all locations efficiently.
    """

    def __init__(self, rows: int = 5, cols: int = 5, dirt_probability: float = 0.4):
        """
        Initialize the vacuum cleaner environment.

        Args:
            rows: Number of rows in the grid
            cols: Number of columns in the grid
            dirt_probability: Probability of a cell starting dirty
        """
        self.rows = rows
        self.cols = cols
        self.dirt_probability = dirt_probability

        # Initialize grid with random dirt
        self.grid = self._initialize_grid()

        # Agent position
        self.position = (0, 0)

        # Performance metrics
        self.actions_taken = []
        self.total_dirt_cleaned = 0
        self.moves_made = 0
        self.suck_actions = 0
        self.idle_actions = 0

        # Initial dirt count
        self.initial_dirt_count = sum(cell == LocationState.DIRTY for row in self.grid for cell in row)
        self.current_dirt_count = self.initial_dirt_count

        # Visited locations (for systematic cleaning)
        self.visited = set()
        self.cleaning_history = []

    def _initialize_grid(self) -> List[List[LocationState]]:
        """Initialize grid with random dirt distribution."""
        grid = []
        for i in range(self.rows):
            row = []
            for j in range(self.cols):
                if random.random() < self.dirt_probability:
                    row.append(LocationState.DIRTY)
                else:
                    row.append(LocationState.CLEAN)
            grid.append(row)
        return grid

    def sense(self) -> LocationState:
        """Sense the current location's dirt status."""
        x, y = self.position
        return self.grid[x][y]

    def act(self, action: Action) -> bool:
        """
        Execute an action and return whether it was successful.

        Returns:
            bool: True if action was executed, False otherwise
        """
        x, y = self.position

        if action == Action.SUCK:
            if self.sense() == LocationState.DIRTY:
                self.grid[x][y] = LocationState.CLEAN
                self.total_dirt_cleaned += 1
                self.current_dirt_count -= 1
                self.suck_actions += 1
                self.cleaning_history.append(('SUCK', self.position))
                return True
            return False

        elif action == Action.MOVE_UP and x > 0:
            self.position = (x - 1, y)
            self.moves_made += 1
            self.cleaning_history.append(('MOVE_UP', self.position))
            return True

        elif action == Action.MOVE_DOWN and x < self.rows - 1:
            self.position = (x + 1, y)
            self.moves_made += 1
            self.cleaning_history.append(('MOVE_DOWN', self.position))
            return True

        elif action == Action.MOVE_LEFT and y > 0:
            self.position = (x, y - 1)
            self.moves_made += 1
            self.cleaning_history.append(('MOVE_LEFT', self.position))
            return True

        elif action == Action.MOVE_RIGHT and y < self.cols - 1:
            self.position = (x, y + 1)
            self.moves_made += 1
            self.cleaning_history.append(('MOVE_RIGHT', self.position))
            return True

        elif action == Action.IDLE:
            self.idle_actions += 1
            self.cleaning_history.append(('IDLE', self.position))
            return True

        return False

    def decide_action(self) -> Action:
        """
        Decision logic for the vacuum cleaner agent.

        Strategy:
        1. If current location is dirty -> SUCK
        2. Otherwise, move to nearest unvisited location (systematic)
        3. If all visited, perform spiral pattern to ensure completeness
        """
        x, y = self.position

        # Rule 1: If dirty, clean it
        if self.sense() == LocationState.DIRTY:
            return Action.SUCK

        # Rule 2: Move to a location that might have dirt
        # Use BFS to find nearest dirty or unvisited cell
        target = self._find_target_cell()

        if target:
            # Determine movement direction
            tx, ty = target
            if tx < x:
                return Action.MOVE_UP
            elif tx > x:
                return Action.MOVE_DOWN
            elif ty < y:
                return Action.MOVE_LEFT
            elif ty > y:
                return Action.MOVE_RIGHT

        # Rule 3: If no target found, perform systematic scan (spiral)
        return self._spiral_next_move()

    def _find_target_cell(self) -> Tuple[int, int]:
        """Find the nearest cell that is either dirty or unvisited."""
        x, y = self.position
        min_distance = float('inf')
        target = None

        # Prioritize dirty cells first
        for i in range(self.rows):
            for j in range(self.cols):
                if self.grid[i][j] == LocationState.DIRTY:
                    distance = abs(i - x) + abs(j - y)
                    if distance < min_distance:
                        min_distance = distance
                        target = (i, j)

        # If no dirty cells, find unvisited cells
        if target is None:
            min_distance = float('inf')
            for i in range(self.rows):
                for j in range(self.cols):
                    if (i, j) not in self.visited:
                        distance = abs(i - x) + abs(j - y)
                        if distance < min_distance:
                            min_distance = distance
                            target = (i, j)

        return target if min_distance > 0 else None

    def _spiral_next_move(self) -> Action:
        """
        Generate next move in a spiral pattern for systematic coverage.
        """
        x, y = self.position

        # Simple spiral: go right, down, left, up with increasing steps
        # Mark current as visited
        self.visited.add(self.position)

        # Try to move in priority order
        if y < self.cols - 1 and (x, y + 1) not in self.visited:
            return Action.MOVE_RIGHT
        elif x < self.rows - 1 and (x + 1, y) not in self.visited:
            return Action.MOVE_DOWN
        elif y > 0 and (x, y - 1) not in self.visited:
            return Action.MOVE_LEFT
        elif x > 0 and (x - 1, y) not in self.visited:
            return Action.MOVE_UP
        else:
            # All visited, go to the nearest cell (any)
            return Action.IDLE

    def run(self, max_steps: int = 1000, visualize: bool = True) -> Dict:
        """
        Run the vacuum cleaner agent.

        Args:
            max_steps: Maximum number of actions to perform
            visualize: Whether to display progress

        Returns:
            Dictionary with performance metrics
        """
        start_time = time.time()

        for step in range(max_steps):
            # Check if environment is clean
            if self.current_dirt_count == 0:
                print(f"\n✓ Environment is CLEAN after {step + 1} steps!")
                break

            # Decide and perform action
            action = self.decide_action()
            self.act(action)
            self.actions_taken.append(action)

            # Mark current position as visited
            self.visited.add(self.position)

            # Visualize occasionally
            if visualize and step % 20 == 0:
                self.display_grid()
                time.sleep(0.1)

        elapsed_time = time.time() - start_time

        # Calculate performance metrics
        metrics = {
            'total_actions': len(self.actions_taken),
            'suck_actions': self.suck_actions,
            'move_actions': self.moves_made,
            'idle_actions': self.idle_actions,
            'total_dirt_cleaned': self.total_dirt_cleaned,
            'initial_dirt_count': self.initial_dirt_count,
            'remaining_dirt': self.current_dirt_count,
            'cleanliness_percentage': (1 - self.current_dirt_count / max(1, self.initial_dirt_count)) * 100,
            'time_taken': elapsed_time,
            'efficiency': self.total_dirt_cleaned / max(1, self.moves_made + self.suck_actions)
        }

        return metrics

    def display_grid(self):
        """Display the current grid state."""
        print(f"\nAgent Position: {self.position}")
        print(f"Dirt Remaining: {self.current_dirt_count}/{self.initial_dirt_count}")
        print("+" + "---" * self.cols)

        for i in range(self.rows):
            row_str = "|"
            for j in range(self.cols):
                if self.position == (i, j):
                    row_str += " 🤖 "  # Agent
                else:
                    row_str += f" {self.grid[i][j].value}  "
                row_str += "|"
            print(row_str)
            print("+" + "---" * self.cols)
        print()

    def plot_performance(self, metrics: Dict):
        """Plot performance metrics."""
        fig, axes = plt.subplots(1, 2, figsize=(12, 5))

        # Action distribution
        actions = ['SUCK', 'MOVE', 'IDLE']
        counts = [metrics['suck_actions'], metrics['move_actions'], metrics['idle_actions']]
        colors = ['green', 'blue', 'gray']

        axes[0].bar(actions, counts, color=colors)
        axes[0].set_title('Action Distribution')
        axes[0].set_ylabel('Count')
        axes[0].set_xlabel('Action Type')

        # Cleanliness progress
        axes[1].bar(['Initial Dirt', 'Remaining Dirt'],
                   [metrics['initial_dirt_count'], metrics['remaining_dirt']],
                   color=['red', 'green'])
        axes[1].set_title(f'Cleaning Performance ({metrics["cleanliness_percentage"]:.1f}% Clean)')
        axes[1].set_ylabel('Number of Dirty Cells')

        plt.suptitle('Vacuum Cleaner Agent Performance', fontsize=14)
        plt.tight_layout()
        plt.show()

def run_multiple_scenarios():
    """Run vacuum cleaner agent on multiple environment configurations."""
    print("\n" + "="*60)
    print("VACUUM CLEANER AGENT - MULTIPLE SCENARIOS")
    print("="*60)

    scenarios = [
        {'name': 'Small Room', 'rows': 3, 'cols': 3, 'dirt': 0.5},
        {'name': 'Standard Room', 'rows': 5, 'cols': 5, 'dirt': 0.4},
        {'name': 'Large Room', 'rows': 7, 'cols': 7, 'dirt': 0.3},
    ]

    all_metrics = []

    for scenario in scenarios:
        print(f"\n📍 Scenario: {scenario['name']}")
        print(f"   Grid: {scenario['rows']}x{scenario['cols']}, Dirt Probability: {scenario['dirt']}")
        print("-" * 40)

        agent = VacuumCleanerAgent(
            rows=scenario['rows'],
            cols=scenario['cols'],
            dirt_probability=scenario['dirt']
        )

        print("Initial Environment:")
        agent.display_grid()

        metrics = agent.run(max_steps=500, visualize=False)
        all_metrics.append((scenario['name'], metrics))

        print(f"\n📊 Results for {scenario['name']}:")
        print(f"   • Total Actions: {metrics['total_actions']}")
        print(f"   • Dirty cells cleaned: {metrics['total_dirt_cleaned']}")
        print(f"   • Cleaning efficiency: {metrics['efficiency']:.2f} dirt/action")
        print(f"   • Time taken: {metrics['time_taken']:.3f} seconds")

        agent.display_grid()
        agent.plot_performance(metrics)

    # Summary comparison
    print("\n" + "="*60)
    print("PERFORMANCE SUMMARY")
    print("="*60)
    print(f"{'Scenario':<15} {'Actions':<10} {'Cleaned':<10} {'Efficiency':<12} {'Clean %':<10}")
    print("-" * 60)
    for name, metrics in all_metrics:
        print(f"{name:<15} {metrics['total_actions']:<10} {metrics['total_dirt_cleaned']:<10} "
              f"{metrics['efficiency']:<12.2f} {metrics['cleanliness_percentage']:<10.1f}")

# Run the complete demonstration
if __name__ == "__main__":
    # Removed headers and assignment details as requested
    # print("="*60)
    # print("ARTIFICIAL INTELLIGENCE ASSIGNMENT")
    # print("Multimedia University of Kenya")
    # print("="*60)

    # print("\n" + "▶"*30)
    # print("QUESTION 1(b): A* SEARCH IMPLEMENTATION")
    # print("◀"*30)
    #run_demo()

    # print("\n" + "▶"*30)
    # print("QUESTION 1(c): TRUTH TABLE ANALYSIS")
    # print("◀"*30)

    # Truth table code
    # print("\nTRUTH TABLE: P \u2227 Q \u2192 R")
    # print(f"{'P':^5} {'Q':^5} {'R':^5} {'P\u2227Q':^8} {'P\u2227Q\u2192R':^10} {'Status':^12}")
    # print("-"*50)

    # NOTE: `itertools` needs to be imported for this section to work.
    # from itertools import product
    # for p, q, r in itertools.product([True, False], repeat=3):
    #     p_and_q = p and q
    #     result = (not p_and_q) or r
    #     status = "Satisfied" if result else "Falsified"
    #     print(f"{str(p)[0]:^5} {str(q)[0]:^5} {str(r)[0]:^5} "
    #           f"{str(p_and_q)[0]:^8} {str(result)[0]:^10} {status:^12}")

    # print("\n" + "▶"*30)
    # print("QUESTION 2(a): PEAS & PAGE ANALYSIS")
    # print("◀"*30)

    # NOTE: `peas` and `page` dictionaries need to be defined for this section to work.
    # print("\n\ud83d\udcca PEAS FRAMEWORK:")
    # for key, values in peas.items():
    #     print(f"\n  {key.upper()}:")
    #     for v in values:
    #         print(f"    \u2022 {v}")

    # print("\n\n\ud83d\udccb PAGE FRAMEWORK:")
    # for key, values in page.items():
    #     print(f"\n  {key.upper()}:")
    #     for v in values:
    #         print(f"    \u2022 {v}")

    # print("\n" + "▶"*30)
    # print("QUESTION 2(b): VACUUM CLEANER AGENT")
    # print("◀"*30)
    run_multiple_scenarios()

    # print("\n" + "="*60)
    # print("ASSIGNMENT COMPLETED SUCCESSFULLY!")
    # print("="*60)